from backend.wallet.transaction import Transaction


class TransactionPool:
    def __init__(self):
        # empty dictionary of key value pairs
        self.transaction_map = {}
    
    # Set a transaction in the transaction pool
    def set_transaction(self, transaction):
        self.transaction_map[transaction.id] = transaction

    # Find a transaction generated by the address
    def existing_transaction(self, address):
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction
